### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by choyg** [jbachand/fitzjs#4]
Hi FitzJS author :wave: 👋 ,

I 🕵am struggling 😾to use this package 📦on account of the typescript definitions not being provided 🚢. I tried to run 🏃`npm install @types/fitzjs` and received the following error 🐛:
![image](https://user-images.githubusercontent.com/15039867/72278670-80fb2a80-3602-11ea-91a8-84dbb5fa0432.png)

please advise 🆘 🆘 🚨 🚨 🚑

**Comment by choyg** [comment]
any update?

**Comment by johnhiggs** [comment]
lfg

**Comment by jbachand** [comment]
@choyg please submit a pr to add

**Comment by jbachand** [comment]
@choyg going to close this if no pr is supplied in 7 days

**Comment by choyg** [comment]
Yo hol up, this wasn't part of our sprint goals

**Comment by mbovahqo** [comment]
let's circle back and sync our swimlanes offline so we can reprioritize our cross team chakras
